global using Microsoft.EntityFrameworkCore;
global using WardrobeAPI.Database;
global using System.ComponentModel.DataAnnotations;
global using System.ComponentModel.DataAnnotations.Schema;
global using WardrobeAPI.Entities;
global using WardrobeAPI.Repositories;
global using Microsoft.AspNetCore.Http;
global using Microsoft.AspNetCore.Mvc;
global using WardrobeAPI.DTOs;