// <auto-generated />
using Microsoft.EntityFrameworkCore;
using Microsoft.EntityFrameworkCore.Infrastructure;
using Microsoft.EntityFrameworkCore.Metadata;
using Microsoft.EntityFrameworkCore.Migrations;
using Microsoft.EntityFrameworkCore.Storage.ValueConversion;
using WardrobeAPI.Database;

#nullable disable

namespace WardrobeAPI.Migrations
{
    [DbContext(typeof(DatabaseContext))]
    [Migration("20230106111902_AddedClosetTable")]
    partial class AddedClosetTable
    {
        protected override void BuildTargetModel(ModelBuilder modelBuilder)
        {
#pragma warning disable 612, 618
            modelBuilder
                .HasAnnotation("ProductVersion", "6.0.12")
                .HasAnnotation("Relational:MaxIdentifierLength", 128);

            SqlServerModelBuilderExtensions.UseIdentityColumns(modelBuilder, 1L, 1);

            modelBuilder.Entity("WardrobeAPI.Entities.Apparel", b =>
                {
                    b.Property<int>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("int");

                    SqlServerPropertyBuilderExtensions.UseIdentityColumn(b.Property<int>("Id"), 1L, 1);

                    b.Property<int>("ClosetId")
                        .HasColumnType("int");

                    b.Property<string>("Color")
                        .IsRequired()
                        .HasColumnType("nvarchar(16)");

                    b.Property<string>("Description")
                        .IsRequired()
                        .HasColumnType("nvarchar(256)");

                    b.Property<string>("Title")
                        .IsRequired()
                        .HasColumnType("nvarchar(32)");

                    b.HasKey("Id");

                    b.HasIndex("ClosetId");

                    b.ToTable("Apparel");

                    b.HasData(
                        new
                        {
                            Id = 1,
                            ClosetId = 1,
                            Color = "Blå",
                            Description = "Den blå skjorte med hvide prikker",
                            Title = "Den blå Skjorte"
                        },
                        new
                        {
                            Id = 2,
                            ClosetId = 2,
                            Color = "Sort",
                            Description = "Det storte wrangler",
                            Title = "Sorte Jeans"
                        });
                });

            modelBuilder.Entity("WardrobeAPI.Entities.Closet", b =>
                {
                    b.Property<int>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("int");

                    SqlServerPropertyBuilderExtensions.UseIdentityColumn(b.Property<int>("Id"), 1L, 1);

                    b.Property<string>("Name")
                        .IsRequired()
                        .HasColumnType("nvarchar(32)");

                    b.HasKey("Id");

                    b.ToTable("Closet");

                    b.HasData(
                        new
                        {
                            Id = 1,
                            Name = "det grå skab"
                        },
                        new
                        {
                            Id = 2,
                            Name = "Det grønne skab"
                        });
                });

            modelBuilder.Entity("WardrobeAPI.Entities.Apparel", b =>
                {
                    b.HasOne("WardrobeAPI.Entities.Closet", "Closet")
                        .WithMany("Apparels")
                        .HasForeignKey("ClosetId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();

                    b.Navigation("Closet");
                });

            modelBuilder.Entity("WardrobeAPI.Entities.Closet", b =>
                {
                    b.Navigation("Apparels");
                });
#pragma warning restore 612, 618
        }
    }
}
